name: touch_fx
description: "A Flutter package that adds dynamic touch-based particle effects — inspired by interactive visuals seen in games and creative apps."
version: 0.0.1
homepage: https://github.com/MarsadMaqsood/snippets-by-marsad

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:
